image: php:7.4

before_script:
  - apt-get update -yqq
  - apt-get install zip unzip -yqq
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php');"

# Run tests with PHP7.0
test:7.0:
  image: php:7.0
  script:
    - apt-get update -yqq
    - apt-get upgrade -y
    - php composer.phar install
    - php vendor/bin/phpunit

# Run tests with PHP7.1
test:7.1:
  image: php:7.1
  script:
    - php composer.phar install
    - php vendor/bin/phpunit

# Run tests with PHP7.2
test:7.2:
  image: php:7.2
  script:
    - php composer.phar install
    - php vendor/bin/phpunit

# Run tests with PHP7.3
test:7.3:
  image: php:7.3
  script:
    - php composer.phar install
    - php vendor/bin/phpunit

# Run tests with PHP7.4
test:7.4:
  image: php:7.4
  script:
    - php composer.phar install
    - php vendor/bin/phpunit
