image: php:7.0

before_script:
  - apt-get update -yqq
  - apt-get install zip unzip -yqq
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php');"

# Run tests with PHP7.0
test:7.0:
  image: php:7.0
  script:
    - php composer.phar install
    - php vendor/bin/phpunit
