image: php:8.2

before_script:
  - apt-get update -yqq
  - apt-get install zip unzip -yqq
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php');"

# Run tests with PHP8.2
test:8.2:
  image: php:8.2
  script:
    - php composer.phar install
    - php vendor/bin/phpunit
